site_name: Learn RL
site_url: https://learnrl.ir
repo_url: https://github.com/SoroushRamezani/mathematics-for-machine-learning-FA-persian
repo_name: mathematics-for-machine-learning-FA-persian
theme:
  language: fa
  logo: assets/logo.png
  favicon: assets/favicon.ico
  name: material
  features:
    - content.code.copy
  font:
    text: Vazirmatn
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
nav:
  - خانه: index.md
  - مثال کد: code-examples.md
  - مثال تب: content-tabs.md
  - ریاضیات برای یادگیری ماشین:
    - 01. مقدمه و انگیزه: mml/1-introduction-and-motivation.md
    - 02. جبر خطی: mml/2-linear-algebra.md
  - شیرجه در یادگیری عمیق:
    - تست: d2dl/text.md

plugins:
  - search:
      lang: ar
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.blocks.caption
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
extra:
  social:
    - icon: simple/telegram 
      link: https://t.me/TheSoroushR
    - icon: simple/github
      link: https://github.com/SoroushRamezani
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css