name: Deploy MkDocs Site

# این اکشن زمانی اجرا می‌شود که کدی به شاخه main پوش شود
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. کد ریپازیتوری را دریافت می‌کند
      - uses: actions/checkout@v4

      # 2. پایتون را برای اجرای MkDocs نصب می‌کند
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. نیازمندی‌های پروژه را از روی فایل requirements.txt نصب می‌کند
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. سایت را با دستور gh-deploy مخصوص گیت‌هاب پیجز منتشر می‌کند
      - name: Deploy site
        run: mkdocs gh-deploy --force